// Nursery price-list parser -- the deterministic half of
// docs/plant-list-import.md. Pure functions: no I/O, no Supabase, no React,
// same input always gives the same output.
//
// A nursery list is one row per species per size, and its price column is what
// they charge YOU. That is `cost`; the sell price is cost x a markup the
// office picks. Column names vary per supplier, so they are guessed here and
// confirmed by a human in the preview before anything is written.
//
// NOTHING IS EVER DROPPED. A malformed row comes back WITH its errors so the
// office can see and fix it; silently skipping rows would let a plant vanish
// between the file and the quote.
//
// Generated by gpt-oss:20b from docs/handoff-plant-import-parser.md and
// verified against 15 assertions. It passed 14; the parseFloat leniency in
// parseMoney was the one failure and is fixed and commented below.

import type { PlantCategory } from "@/lib/plantProducts";

export type ImportField = "name" | "botanical_name" | "category" | "size" | "cost";

export type ColumnMapping = Partial<Record<ImportField, number>>;

export type ParsedFile = { headers: string[]; rows: string[][] };

export type ImportRow = {
  rowNumber: number;
  name: string;
  botanical_name: string | null;
  category: PlantCategory;
  size: string;
  cost: number;
  unit_price: number;
  errors: string[];
};

export function parseDelimited(text: string): ParsedFile {
  // Strip UTF-8 BOM if present
  if (text.charCodeAt(0) === 0xFEFF) {
    text = text.slice(1);
  }

  const lines = text.split(/\r?\n/);
  const rows: string[][] = [];
  let headers: string[] = [];
  let firstNonBlankFound = false;
  const delimiter = lines[0]?.includes("\t") ? "\t" : ",";

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (line === "") continue; // skip blank lines

    const parsedFields = parseLine(line, delimiter);
    if (!firstNonBlankFound) {
      headers = parsedFields.map((f) => f.trim());
      firstNonBlankFound = true;
    } else {
      rows.push(parsedFields.map((f) => f.trim()));
    }
  }

  return { headers, rows };
}

function parseLine(line: string, delimiter: string): string[] {
  const fields: string[] = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        // Check for escaped quote
        if (i + 1 < line.length && line[i + 1] === '"') {
          field += '"';
          i++; // skip the escaped quote
        } else {
          inQuotes = false;
        }
      } else {
        field += ch;
      }
    } else {
      if (ch === delimiter) {
        fields.push(field);
        field = "";
      } else if (ch === '"') {
        inQuotes = true;
      } else {
        field += ch;
      }
    }
  }
  fields.push(field);
  return fields;
}

export function guessColumnMapping(headers: string[]): ColumnMapping {
  const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");
  const mapping: ColumnMapping = {};

  const fieldKeys: Record<ImportField, string[]> = {
    botanical_name: [
      "botanical",
      "botanicalname",
      "latin",
      "latinname",
      "scientificname",
    ],
    name: [
      "common",
      "commonname",
      "name",
      "plant",
      "plantname",
      "description",
      "item",
    ],
    size: ["size", "container", "cont", "pot", "potsize", "containersize", "grade"],
    cost: [
      "price",
      "cost",
      "yourcost",
      "wholesale",
      "wholesaleprice",
      "ea",
      "each",
      "unitprice",
      "net",
    ],
    category: ["category", "type", "class", "planttype"],
  };

  // Order matters: botanical_name before name
  const order: ImportField[] = [
    "botanical_name",
    "name",
    "size",
    "cost",
    "category",
  ];

  for (const field of order) {
    const keys = fieldKeys[field];
    for (let i = 0; i < headers.length; i++) {
      const norm = normalize(headers[i]);
      if (keys.includes(norm)) {
        mapping[field] = i;
        break;
      }
    }
  }

  return mapping;
}

export function parseMoney(raw: string): number | null {
  const trimmed = raw.trim();
  if (
    trimmed === "" ||
    trimmed === "N/A" ||
    trimmed === "CALL" ||
    trimmed === "—" ||
    trimmed === "TBD" ||
    trimmed === "-"
  ) {
    return null;
  }
  if (trimmed.includes("-")) {
    // Negative prices are invalid
    return null;
  }

  // Remove $ , spaces and trailing dot
  const cleaned = trimmed.replace(/[$,\s]/g, "").replace(/\.$/, "");
  if (cleaned === "") return null;

  // parseFloat is lenient: it reads "12 each" as 12 and "3 gal" as 3. A cell
  // that is not ENTIRELY a number is not a price -- a nursery writing
  // "12 each" or "call for 24in" must come back as null so the office sees an
  // error, not a silently truncated number.
  if (!/^\d+(\.\d+)?$/.test(cleaned)) return null;

  const parsed = parseFloat(cleaned);
  if (!isFinite(parsed)) return null;
  return parsed;
}

export function buildImportRows(
  file: ParsedFile,
  mapping: ColumnMapping,
  markupMultiple: number
): ImportRow[] {
  const allowedCategories: PlantCategory[] = [
    "tree",
    "palm",
    "shrub",
    "perennial",
    "grass",
    "annual",
    "groundcover",
  ];

  const rows: ImportRow[] = [];

  for (let i = 0; i < file.rows.length; i++) {
    const rawRow = file.rows[i];
    const errors: string[] = [];
    const rowNumber = i + 1;

    // Helper to get cell by mapping
    const getCell = (field: ImportField): string | undefined => {
      const idx = mapping[field];
      if (idx === undefined) return undefined;
      return rawRow[idx];
    };

    // Botanical name
    const botanicalCell = getCell("botanical_name");
    const botanical_name =
      botanicalCell !== undefined && botanicalCell !== "" ? botanicalCell : null;

    // Name with fallback
    const nameCell = getCell("name");
    let name = "";
    if (nameCell !== undefined && nameCell !== "") {
      name = nameCell;
    } else if (botanical_name !== null) {
      name = botanical_name;
    } else {
      errors.push("No plant name");
      name = "";
    }

    // Size
    const sizeCell = getCell("size");
    let size = "";
    if (sizeCell !== undefined && sizeCell !== "") {
      size = sizeCell;
    } else {
      errors.push("Missing size");
      size = "";
    }

    // Cost
    const costCell = getCell("cost");
    let cost = 0;
    if (costCell !== undefined) {
      const parsed = parseMoney(costCell);
      if (parsed === null) {
        errors.push(`Could not read price "${costCell}"`);
        cost = 0;
      } else {
        cost = parsed;
      }
    } else {
      errors.push(`Could not read price ""`);
      cost = 0;
    }

    // Category
    const categoryCell = getCell("category");
    let category: PlantCategory = "shrub";
    if (categoryCell !== undefined) {
      const cat = categoryCell.trim().toLowerCase() as PlantCategory;
      if (allowedCategories.includes(cat)) {
        category = cat;
      }
    }

    // Unit price
    let unit_price = 0;
    if (typeof markupMultiple === "number" && isFinite(markupMultiple) && markupMultiple > 0) {
      unit_price = Math.round(cost * markupMultiple * 100) / 100;
    } else {
      unit_price = 0;
      errors.push("Invalid markup");
    }

    rows.push({
      rowNumber,
      name,
      botanical_name,
      category,
      size,
      cost,
      unit_price,
      errors,
    });
  }

  return rows;
}
