-- Quotes: customer "send" flow. Adds a per-quote share_token used by the
-- frictionless public customer link (/q/{token}). The token is generated by the
-- app when office hits Send and rotates on each (re)send, so old links stop
-- working. Idempotent + additive — no data destroyed, no string literals (the
-- Supabase SQL Editor mangles pasted single quotes into double quotes, so this
-- file is intentionally literal-free). Run via SQL Editor (paste from Notepad)
-- BEFORE deploying the send code.
--
-- The approve/reject-by-token logic lives in the /api/quotes/by-token/[token]/decide
-- route (service role), mirroring the approve_quote / reject_quote RPCs that the
-- logged-in customer portal uses. No new RPCs needed here.
begin;
alter table public.quotes
  add column if not exists share_token uuid;

create unique index if not exists quotes_share_token_key
  on public.quotes (share_token);
commit;